### ISSUE TITLE
Problem with install (application minimized)

### ISSUE THREAD

**Issue by SergeyMelnyk** [Bruno-Furtado/react-native-sms-retriever#25]
### Environment

* react-native: "0.60.5",
* Platform: Android
* Device: Which One
* react-native-sms-retriever: "^1.1.1",
* Build Tools Version (Android only)

### Description

I have problem, after install my app just show splash screen and minimized automatically

**Comment by Bruno-Furtado** [comment]
@SergeyMelnyk are you talking about the example app of this repo? Or do you have a problem with another app that is using `react-native-sms-retriever`?

**Comment by SergeyMelnyk** [comment]
@Bruno-Furtado hi, i talk about my app not this repo, and i found solution, so:

in logcat: `adb locat *:E` was error 

> Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.zza" 

after I edit my manifest

> dependencies {
  provided "com.facebook.react:react-native:+"
  -compile "com.google.android.gms:play-services-base:10.2.4"
  -compile "com.google.android.gms:play-services-maps:10.2.4"
  +compile "com.google.android.gms:play-services-base:+"
  +compile "com.google.android.gms:play-services-maps:+"
}

after this app work again, maybe this solution help other people

**Comment by Bruno-Furtado** [comment]
@SergeyMelnyk, thanks for sharing.

It looks like we had a dependencies incompatibility. The SMS Retriever module is using `v17.0.0` of `com.google.android.gms` and your app is using `v10.2.4`. When you change to `+`, it worked because you are using the latest version of these dependencies.

I can work to improve it on the module side. Give some days and I will publish this improvement.
